### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by SaranshSharmaShorthillsAI**
changed "which exposes convenience methods to that exposes convenient methods".

### CODE REVIEW

**Comment by ShorthillsAI** [comment]
@SaranshSharmaShorthillsAI , Please resolve the conflicts by changing "AI Messages to AIMessages" as explained in the conflict message.

**Comment by SaranshSharmaShorthillsAI** [comment]
Changed "AI Messages to AIMessages".

**Comment by SaranshSharmaShorthillsAI** [comment]
Changed "Human Messages to HumanMessages".

**Comment by SaranshSharmaShorthillsAI** [comment]
Changed "AImessages to AIMessages".

**Review by ShorthillsAI — APPROVED** [review]

**Comment by SaranshSharmaShorthillsAI** [comment]
changed "an prediction to a prediction" and "to get ALLL the deets" to "to get ALL the deets"

**Pull request closed without merging**
